title: <p align="center"> Macarena </p>

logo: "images/foto_port.jpg"

description:
  <p align="justify">
  Soy Doctora en estadística interesada en la astronomía y el trekking. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
